export const banks = [
{name:"City Bank",fdr:10.5,tech:9,cards:10,atm:7,type:["pro","women"],bestFor:"Cards"},
{name:"DBBL",fdr:9.5,tech:9,cards:6,atm:10,type:["student","all"],bestFor:"ATM"},
{name:"BRAC",fdr:10.2,tech:8,cards:8,atm:8,type:["pro","women"],bestFor:"Service"},
{name:"EBL",fdr:10.0,tech:9,cards:9,atm:7,type:["pro","student"],bestFor:"Travel"},
{name:"Standard Chartered",fdr:8.5,tech:8,cards:10,atm:6,type:["pro"],bestFor:"International"},
{name:"Islami Bank",fdr:10.1,tech:7,cards:6,atm:9,type:["all","nrb"],bestFor:"Shariah"},
{name:"MTB",fdr:10.7,tech:9,cards:9,atm:7,type:["pro"],bestFor:"Premium"},
{name:"Bank Asia",fdr:10.0,tech:8,cards:7,atm:9,type:["nrb","all"],bestFor:"Agent Banking"},
{name:"UCB",fdr:10.3,tech:8,cards:8,atm:8,type:["pro","all"],bestFor:"Corporate"},
{name:"Prime Bank",fdr:10.4,tech:8,cards:9,atm:7,type:["pro"],bestFor:"Investment"},
{name:"IFIC",fdr:10.5,tech:7,cards:7,atm:9,type:["all"],bestFor:"Micro Saving"},
{name:"HSBC",fdr:8.0,tech:9,cards:10,atm:6,type:["pro"],bestFor:"Expat"},
{name:"Trust Bank",fdr:10.3,tech:8,cards:8,atm:7,type:["pro"],bestFor:"Security"},
{name:"Pubali",fdr:9.8,tech:6,cards:6,atm:10,type:["all"],bestFor:"Network"},
{name:"NCC",fdr:10.6,tech:7,cards:7,atm:8,type:["pro","all"],bestFor:"Remittance"},
{name:"Jamuna",fdr:10.4,tech:7,cards:7,atm:8,type:["all"],bestFor:"Loans"},
{name:"Mercantile",fdr:10.5,tech:7,cards:7,atm:7,type:["pro"],bestFor:"Corporate"},
{name:"Social Islami",fdr:10.2,tech:6,cards:6,atm:8,type:["all"],bestFor:"Charity"},
{name:"Dhaka Bank",fdr:10.4,tech:8,cards:8,atm:7,type:["pro"],bestFor:"Trade"},
{name:"AB Bank",fdr:10.1,tech:7,cards:7,atm:7,type:["all"],bestFor:"Legacy"},
{name:"Southeast",fdr:10.2,tech:7,cards:7,atm:8,type:["all"],bestFor:"SME"},
{name:"Al-Arafah",fdr:10.3,tech:6,cards:6,atm:8,type:["all"],bestFor:"Islamic"},
{name:"EXIM",fdr:10.4,tech:7,cards:7,atm:7,type:["all"],bestFor:"Export"},
{name:"NRB Bank",fdr:10.2,tech:7,cards:6,atm:7,type:["nrb"],bestFor:"NRB"},
{name:"NRBC",fdr:10.3,tech:7,cards:7,atm:8,type:["nrb"],bestFor:"Remittance"},
{name:"Midland",fdr:10.1,tech:8,cards:7,atm:7,type:["pro"],bestFor:"Digital"},
{name:"Modhumoti",fdr:10.0,tech:7,cards:6,atm:7,type:["all"],bestFor:"General"},
{name:"Meghna",fdr:10.0,tech:7,cards:6,atm:7,type:["all"],bestFor:"Retail"},
{name:"Union Bank",fdr:10.2,tech:7,cards:6,atm:7,type:["all"],bestFor:"Growth"},
{name:"Community Bank",fdr:10.3,tech:8,cards:7,atm:7,type:["pro"],bestFor:"Security"}
];
